> ### 2020.01.20 월요일

1. 기계학습과 딥러닝의 차이점은?

2. 경사하강법 그림으로 표현하면?

3. 가중치는 신경망의 어디에 해당하는가?
<br> 신경전달물질
<br> 시냅스에서 분포 됨(축삭말단과 수상돌기 사이)


4. 어떻게 다층으로 복잡한 문제를 풀 수 있는가?

5. 다층 네트웍을 학습시키기가 어려운 이유는?


6. 활성화는 비선형이어야 하는가?

7. sigmoid 함수의 장점?

8. y = wx + b 에서 b는 왜 필요한가?
<br> b 는 전체를 들었다 놨다 하는 것이라서(전체에 다 더하는 것) 조금만 변해도 큰 변화
<br> 원점을 지나는 것은 큰 제약조건.



9. 딥러닝의 핵심 돌파구?

10. 왜 CNN을 특징 추출과 분류기결합으로 보는가?


In [1]:
import numpy as np
import numpy.linalg as lin

In [11]:
a = np.array([[1,1],[2,1]])
print(a)
print(a.shape)

a_ = lin.inv(a)
print(a_)

y = np.array([2,4])  # 행렬로 정의해줘야지 나중에 연산할 때 편하다.
print(y.shape)
# y 는 컬럼벡터(한 컬럼짜리 행렬)로 표현해줘야 정확한 수식이 된다.
y_1 = np.array([[2,4]])
y_2 = np.array([[2],[4]])
print(y_1.shape)
print(y_2.shape)

y = np.array([2,4]).reshape(2,1)
print(y)

[[1 1]
 [2 1]]
(2, 2)
[[-1.  1.]
 [ 2. -1.]]
(2,)
(1, 2)
(2, 1)
[[2]
 [4]]


In [12]:
w = np.matmul(a_, y) 
print(w)

[[2.]
 [0.]]


In [17]:
a = np.array([[1,1],[2,1],[3,1]])

# a_ = lin.inv(a)  정방 행렬이 아니라서 계산될 수 없음. pinv사용하기
a_ = lin.pinv(a)
print(a_)

y = np.array([2,4,6.4]).reshape(3,1)
w = np.matmul(a_,y)
print(w)

[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]
[[ 2.2       ]
 [-0.26666667]]


In [18]:
# y = wx + b
y = w[0,0] * 1 + w[1,0] 
print(y)   
# 학습데이터를 가장 잘 설명할 수 있는 직선이 나오는 것이지, 점을 지나는 것이 아니다. 오차가 존재.
# 테스트하기 힘듦. 
# 그래서 수식을 바꿔줘야한다.
# np.matmul(w, np.array([1,1]))

1.9333333333333322


In [19]:
y = w[0,0] * np.array([-3,-2,-1,0,1,2,3]) + w[1,0] 
# 각각을 다 곱해주는 연산을 함. (브로드캐스팅 개념...)
print(y)

[-6.86666667 -4.66666667 -2.46666667 -0.26666667  1.93333333  4.13333333
  6.33333333]
